// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
        int N = Integer.parseInt(args[0]); 

        int a = 0;  
        int b = 0; 

        for (int i = 0; i < N; i++) {
            double r = Math.random(); 

            if (r > 0.5)
                a++;
            else
                b++;
        }

        System.out.println("> 0.5: " + a + " times");
        System.out.println("<= 0.5: " + b + " times");

        if (b == 0)
            System.out.println("Ratio: undefined (division by zero)");
        else
            System.out.println("Ratio: " + (double) a / b);
	}
}
